import os
import json
from datetime import datetime

from layer3.checks import (
    check_pii_leakage,
    check_toxicity,
    check_system_leakage,
    check_apology_loop
)

def log_event(action, metric, reason, original_text):
    """Logs the Layer 3 interception to the security audit log."""
    logs_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "logs")
    log_file = os.path.join(logs_dir, "security_audit.log")
    
    event = {
        "timestamp": datetime.now().isoformat(),
        "layer": "Layer 3 (Output Guard)",
        "action": action,
        "detection_metric": metric,
        "reason": reason,
        "flagged_output": original_text[:200] + "..." if len(original_text) > 200 else original_text
    }
    
    try:
        os.makedirs(logs_dir, exist_ok=True)
        with open(log_file, "a") as f:
            f.write(json.dumps(event) + "\n")
    except Exception as e:
        print(f"Failed to write to audit log: {e}")

def layer3_output_filter(generated_response: str) -> tuple[bool, str, str]:
    """
    Validates the strictly final LLM generation string before sending it to the user.
    Returns: (is_safe, sanitized_response, status_message)
    """
    print("\n[Layer 3 - Output Guard] Validating LLM generation...")
    
    # 1. Check for Toxicity
    if check_toxicity(generated_response):
        print("  ❌ 1. TOXICITY DETECTED: Triggered hard-block.")
        log_event("BLOCKED_OUTPUT", "Toxicity Match", "The generated response contained restricted toxic terminology.", generated_response)
        return False, "Response Blocked: The output violated Corporate Communication guidelines.", "Toxicity Detected"
        
    # 2. Check for PII Data Leakage
    if check_pii_leakage(generated_response):
        print("  ❌ 2. DATA LEAK DETECTED: Triggered hard-block.")
        log_event("BLOCKED_OUTPUT", "PII/Data Leakage", "The generated response contained suspected PII (SSN/CC).", generated_response)
        return False, "Response Blocked: The output attempted to reveal sensitive Personally Identifiable Information.", "PII Leakage Detected"
        
    # 3. Check for System/Code Leakage
    if check_system_leakage(generated_response):
        print("  ❌ 3. SYSTEM LEAK DETECTED: Triggered hard-block.")
        log_event("BLOCKED_OUTPUT", "System/Code Leakage", "The generated response hallucinated executable commands or paths.", generated_response)
        return False, "Response Blocked: The output hallucinated unauthorized system-level code or configuration paths.", "System Leakage Detected"
        
    # 4. Check for Apology Boilerplate generated by base LLM constraints
    if check_apology_loop(generated_response):
        print("  ⚠️ 4. APOLOGY LOOP DETECTED: Overwriting generic LLM refusal.")
        log_event("OVERRODE_APOLOGY", "Apology Boilerplate", "The LLM fell back to an evasive apology loop.", generated_response)
        # We return True here so that Streamlit doesn't show a red error, but we actively overwrite the text string!
        return True, "Security Lock: The system cannot fulfill this request due to SecureRAG compliance policies.", "Apology Override"
        
    print("  ✅ Output Validation Complete. No anomalies.")
    # Safe - Output is clean!
    return True, generated_response, "SAFE: The output passed all validations."
