import pandas as pd
import pickle
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Ensure the models directory exists
os.makedirs("models", exist_ok=True)

# Load the real dataset generated by build_hf_dataset.py
try:
    df = pd.read_csv("models/training_dataset.csv")
    print(f"Loaded dataset from models/training_dataset.csv")
    print(f"Total samples: {len(df)} ({len(df[df['label'] == 0])} safe, {len(df[df['label'] == 1])} malicious).")
except FileNotFoundError:
    print("Error: models/training_dataset.csv not found!")
    print("Please run `python layer1/build_hf_dataset.py` first to download the data.")
    exit(1)

# Split into X and y
X = df["text"]
y = df["label"]

# Train TF-IDF vectorizer
print("Training TF-IDF Vectorizer...")
vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1, 2))
X_vec = vectorizer.fit_transform(X)

# Train Logistic Regression Model
print("Training Logistic Regression Model...")
model = LogisticRegression(C=1.0, max_iter=1000)
model.fit(X_vec, y)

# Evaluate on training data (just to show it learned)
y_pred = model.predict(X_vec)
acc = accuracy_score(y, y_pred)
print(f"Training Accuracy: {acc * 100:.2f}%")

# Save Models
print("Saving models to models/ directory...")
with open("models/layer1_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

with open("models/layer1_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("ML Training Complete! Models saved.")
